### ISSUE TITLE
Support for XML layouts

### ISSUE THREAD

**Issue by iPaulPro** [openaphid/android-flip#13]
I've submitted a pull request for commit https://github.com/iPaulPro/android-flip/commit/76b2b361972b6bdd4f2ae75d74e82e2810e5af14, which adds the constructors needed to support the XML layout editor. It is now part of my outstanding pull, https://github.com/openaphid/android-flip/pull/10.

Users can add FlipViewController to their XML layouts like this:

```
<com.aphidmobile.flip.FlipViewController 
    xmlns:custom="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    custom:orientation="horizontal" />
```

The `custom:orientation` is an **optional** custom parameter that controls the orientation of the flip. This defaults to _vertical_. 

I've also updated the Demo project to include an [example of FlipViewController used in XML](https://github.com/iPaulPro/android-flip/blob/master/FlipView/Demo/src/com/aphidmobile/flip/demo/FlipTextViewXmlActivity.java).

**Comment by Ni3Narale** [comment]
@iPaulPro Hello dude Please add example project I got 404 for link
and it is possible to refresh to pull down and end of the view load more..
if there is any solution pls forward the links..
thanks..
