### ISSUE TITLE
feature: flipping View larger than FlipViewController View

### ISSUE THREAD

**Issue by quintos** [openaphid/android-flip#3]
Hi,

I'm using the ActionBar pattern in my app and i want the AB to be included in the Flipping animation (so the whole screen is part of the page) but i can't include the AB in the FlipViewController layout. I can imagine that is could be possibe to create snapshots of the whole screen even when the FlipViewController is only a part of the screen so the AB would also be flipping. (is it?) but when the user reaches the last page and the page bouces back, the AB must not be visible behind the last page. So i need to hide the AB at runtime at the moment the last page is being flipped/bounced. Is it possible to listen for such an event? Or is there a better way?

Thanks!

**Comment by kamran41** [comment]
please anyone can tell me how we  setCurrentItem of FlipViewController class????
