### ISSUE TITLE
Flip Animation on setSelection

### ISSUE THREAD

**Issue by junghie** [openaphid/android-flip#31]
Good Day,

Thanks for these awesome library find it very useful on my new project.
just want to ask on how can we implement the flip animation on setSelection method FlipViewController,java? or is there another way to jump between pages with flip animation?

**Comment by gaurangtalati** [comment]
@pekoe have you tried the back flip.. i have put forward as false .. keeping all the things same.. Still getting no result..

**Comment by luccastanan** [comment]
Someone got the back flip?

**Comment by gaurangtalati** [comment]
For Back Flip.. use this guys..


controller.showFlipAnimation();
        forward = false;
        swapCards();
        frontCards.resetWithIndex(backCards.getIndex() - 1);
        controller.flippedToView(getPageIndexFromAngle(accumulatedAngle-1), false);
        setState(STATE_AUTO_ROTATE);
        controller.getSurfaceView().requestRender();


working perfectly for me

**Comment by luccastanan** [comment]
Somewhere in my method FlipCards.java class?

**Comment by luccastanan** [comment]
Your code is fine, but in addition takes 2 seconds to work it skip a page, such as going from page 3 to 1, have any of that to change?

**Comment by gaurangtalati** [comment]
My data was coming from database.. so i just have to manage the flips..
I will try this things.. and as soon as i get anything.. will give you an
update..


*Regards*

*Gaurang Talati*
*Software Developer*
*Credencys Solutions Inc.*
*13th Floor, Landmark Building, PrahladNagar, **Ahmedabad, 380051*

*Mobile:  +91- 7383933533 *
